/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/smoke-test/hello-world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt */
        get: operations["prompt_smoke_test_hello_world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/external-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * External Login
         * @description Get the auth redirect URL
         */
        get: operations["external_login_api_v1_users_external_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/auth-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Callback */
        get: operations["auth_callback_api_v1_users_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Access Token
         * @description Refresh the access token using a valid refresh token.
         */
        post: operations["refresh_access_token_api_v1_users_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Profile */
        get: operations["get_user_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete User Account
         * @description Delete the authenticated user's account
         *
         *     Args:
         *         hard_delete: If True, permanently removes all user data. If False, soft-deletes the account.
         *
         *     Returns:
         *         No content on success
         */
        delete: operations["delete_user_account_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Profile Image */
        post: operations["upload_profile_image_api_v1_users_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/primary-qwirl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Primary Qwirl
         * @description Get the user's primary Qwirl
         *
         *     Returns:
         *         The user's primary Qwirl or an error if none is set
         */
        get: operations["get_primary_qwirl_api_v1_users_primary_qwirl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Posts
         * @description Get posts created by a user
         *
         *     Args:
         *         user_id: ID of the user whose posts to retrieve (defaults to authenticated user)
         *         skip: Number of posts to skip for pagination
         *         limit: Maximum number of posts to return
         *
         *     Returns:
         *         List of posts created by the user
         */
        get: operations["get_user_posts_api_v1_users_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User By Id
         * @description Get a user's profile by user ID with relationship status
         *
         *     Args:
         *         user_id: ID of the user to retrieve
         *
         *     Returns:
         *         User profile with relationship status information
         */
        get: operations["get_user_by_id_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qwirls
         * @description Get all qwirls of a user
         *
         *     Returns:
         *         Qwirls
         */
        get: operations["get_qwirls_api_v1_qwirl__get"];
        put?: never;
        /**
         * Add Qwirl
         * @description Add new qwirl
         *
         *     Returns:
         *         qwirl
         */
        post: operations["add_qwirl_api_v1_qwirl__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl/{qwirl_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qwirl Id
         * @description Get qwirl by qwirl id
         *
         *     Returns:
         *         Qwirl
         */
        get: operations["get_qwirl_id_api_v1_qwirl__qwirl_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Qwirl
         * @description Delete a qwirl
         *
         *     Returns:
         *         Failure or 204
         */
        delete: operations["delete_qwirl_api_v1_qwirl__qwirl_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Qwirl
         * @description Update a qwirl of logged in user
         *
         *     Args:
         *         qwirl_id (int): qwirl id
         *
         *     Returns:
         *         Qwirl
         */
        patch: operations["update_qwirl_api_v1_qwirl__qwirl_id__patch"];
        trace?: never;
    };
    "/api/v1/qwirl/user/{user_id}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Primary Qwirl
         * @description Get the primary Qwirl of a specific user
         *
         *     Args:
         *         user_id (int): The ID of the user whose primary Qwirl to retrieve
         *
         *     Returns:
         *         The user's primary Qwirl or an appropriate error
         */
        get: operations["get_user_primary_qwirl_api_v1_qwirl_user__user_id__primary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Profile Qwirl
         * @description Get the current user's own Profile Qwirl for viewing or editing.
         *
         *     Returns:
         *         The user's Profile Qwirl with all items (including soft-deleted ones)
         */
        get: operations["get_my_profile_qwirl_api_v1_qwirl_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl/me/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Profile Qwirl Item
         * @description Adds a new poll item to the user's Profile Qwirl.
         *
         *     Args:
         *         item_data: The question, options, and owner's answer
         *
         *     Returns:
         *         The newly created QwirlItem
         */
        post: operations["add_profile_qwirl_item_api_v1_qwirl_me_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl/me/items/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Profile Qwirl Items
         * @description Changes the order of multiple poll items in the user's Profile Qwirl.
         *
         *     Args:
         *         reorder_data: List of items with their new positions
         *
         *     Returns:
         *         200 OK if successful
         */
        patch: operations["reorder_profile_qwirl_items_api_v1_qwirl_me_items_reorder_patch"];
        trace?: never;
    };
    "/api/v1/qwirl/me/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Profile Qwirl Item
         * @description Permanently deletes a poll item from the user's Profile Qwirl.
         *     This is a destructive action and will also remove all associated responses.
         *
         *     Args:
         *         item_id: The ID of the item to delete
         *
         *     Returns:
         *         204 No Content if successful
         */
        delete: operations["delete_profile_qwirl_item_api_v1_qwirl_me_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Profile Qwirl Item
         * @description Updates a single Qwirl item (text, options, answer, or soft-delete status).
         *
         *     Args:
         *         item_id: The ID of the item to update
         *         update_data: The fields to update
         *
         *     Returns:
         *         The updated QwirlItem
         */
        patch: operations["update_profile_qwirl_item_api_v1_qwirl_me_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/qwirl-responses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Qwirl Response
         * @description Add new qwirl
         *
         *     Returns:
         *         qwirl
         */
        post: operations["add_qwirl_response_api_v1_qwirl_responses__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qwirl-responses/{response_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qwirl Response By Id
         * @description Get qwirl response by id
         *
         *     Returns:
         *         Qwirl
         */
        get: operations["get_qwirl_response_by_id_api_v1_qwirl_responses__response_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Qwirl Response
         * @description Delete a qwirl response
         *
         *     Returns:
         *         Failure or 204
         */
        delete: operations["delete_qwirl_response_api_v1_qwirl_responses__response_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Get all categories
         *
         *     Returns:
         *         Categories
         */
        get: operations["get_categories_api_v1_question_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-bank/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Question Bank */
        get: operations["search_question_bank_api_v1_question_bank_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Post */
        post: operations["create_post_api_v1_post_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/post/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_v1_post__post_id__delete"];
        options?: never;
        head?: never;
        /** Update Post */
        patch: operations["update_post_api_v1_post__post_id__patch"];
        trace?: never;
    };
    "/api/v1/post/user/{post_owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Posts */
        get: operations["list_my_posts_api_v1_post_user__post_owner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/post/{post_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Vote */
        post: operations["add_vote_api_v1_post__post_id__vote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/post/{post_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like Post */
        post: operations["like_post_api_v1_post__post_id__like_post"];
        /** Unlike Post */
        delete: operations["unlike_post_api_v1_post__post_id__like_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Followers */
        get: operations["get_user_followers_api_v1_user_follows_followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Following
         * @description Get list of users that the current user is following
         */
        get: operations["get_user_following_api_v1_user_follows_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Friends
         * @description Get list of user's friends
         */
        get: operations["get_user_friends_api_v1_user_follows_friends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Followers By Id
         * @description Get list of followers for a specific user
         */
        get: operations["get_user_followers_by_id_api_v1_user_follows__user_id__followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/{user_id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Following By Id
         * @description Get list of users that a specific user is following
         */
        get: operations["get_user_following_by_id_api_v1_user_follows__user_id__following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/{user_id}/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Friends By Id
         * @description Get list of friends for a specific user
         */
        get: operations["get_user_friends_by_id_api_v1_user_follows__user_id__friends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/relationship/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relationship
         * @description Get relationship status with another user
         */
        get: operations["get_relationship_api_v1_user_follows_relationship__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/follow/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow User
         * @description Follow a user
         */
        post: operations["follow_user_api_v1_user_follows_follow__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/unfollow/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unfollow User
         * @description Unfollow a user
         */
        post: operations["unfollow_user_api_v1_user_follows_unfollow__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_follows/common_friends/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Common Friends
         * @description Get list of friends that are common between the current user and another user
         */
        get: operations["get_common_friends_api_v1_user_follows_common_friends__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** Body_upload_profile_image_api_v1_users_avatar_post */
        Body_upload_profile_image_api_v1_users_avatar_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemReorderEntry */
        ItemReorderEntry: {
            /** Item Id */
            item_id: number;
            /** New Position */
            new_position: number;
        };
        /** PostAttachment */
        PostAttachment: {
            /** Text Content */
            text_content?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Question Text */
            question_text?: string | null;
            /** Duration */
            duration?: number | null;
            /** Question Bank Id */
            question_bank_id?: number | null;
        };
        /** PostBase */
        PostBase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text Content */
            text_content?: string;
            /** Question Text */
            question_text?: string;
            /** Question Bank Id */
            question_bank_id?: number | null;
            /** Options */
            options?: string[] | null;
            /** Selected Option Index */
            selected_option_index?: number | null;
            /**
             * Is Mine
             * @default true
             */
            is_mine: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Duration */
            duration?: number | null;
            /** Results */
            results?: Record<string, never>[] | null;
        };
        /** PostCreate */
        PostCreate: {
            post_attachment: components["schemas"]["PostAttachment"];
            /** Options */
            options?: string[] | null;
            /** Selected Option Index */
            selected_option_index?: number | null;
        };
        /** PostFetchByID */
        PostFetchByID: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text Content */
            text_content?: string;
            /** Question Text */
            question_text?: string;
            /** Question Bank Id */
            question_bank_id?: number | null;
            /**
             * Likes Count
             * @default 0
             */
            likes_count: number;
            /**
             * Comments Count
             * @default 0
             */
            comments_count: number;
            /**
             * Shares Count
             * @default 0
             */
            shares_count: number;
            /** Options */
            options?: string[] | null;
            /** Author Selected Option Index */
            author_selected_option_index?: number | null;
            /**
             * Is Mine
             * @default true
             */
            is_mine: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Duration */
            duration?: number | null;
            /** Results */
            results?: Record<string, never>[] | null;
            /** My Selected Option Index */
            my_selected_option_index?: number | null;
            /**
             * Is Liked
             * @default false
             */
            is_liked: boolean | null;
        };
        /** PostResponse */
        PostResponse: {
            /** Id */
            id: number;
            /** Content */
            content: string;
            /** Media Urls */
            media_urls?: string[] | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Likes Count
             * @default 0
             */
            likes_count: number;
            /**
             * Comments Count
             * @default 0
             */
            comments_count: number;
            /**
             * Is Liked
             * @default false
             */
            is_liked: boolean | null;
        };
        /** QuestionSearchResponse */
        QuestionSearchResponse: {
            /** Id */
            id: number;
            /** Question Text */
            question_text: string;
            /** Options */
            options: string[];
            /** Tags */
            tags: string[];
            /** Categories Id */
            categories_id: number;
            /** Category Name */
            category_name: string;
        };
        /** QwirlAnswer */
        QwirlAnswer: {
            /** Question Id */
            question_id: number | null;
            /** Answer */
            answer: string | null;
            /** Comment */
            comment: string | null;
        };
        /** QwirlAnswerCreate */
        QwirlAnswerCreate: {
            /** Question Id */
            question_id: number;
            /** Answer */
            answer: string;
            /** Comment */
            comment: string;
        };
        /** QwirlBase */
        QwirlBase: {
            /** Id */
            id: number;
            /** Questions */
            questions: components["schemas"]["QwirlQuestion"][] | null;
            /** Tags */
            tags: string[] | null;
            /** Created By */
            created_by: number | null;
            user: components["schemas"]["QwirlUser"] | null;
        };
        /** QwirlCreate */
        QwirlCreate: {
            /** Questions */
            questions: components["schemas"]["QwirlQuestionCreate"][];
            /** Tags */
            tags: string[];
        };
        /** QwirlItemCreate */
        QwirlItemCreate: {
            /** Question Text */
            question_text: string;
            /** Options */
            options: string[];
            /** Owner Answer */
            owner_answer: string;
        };
        /** QwirlItemUpdate */
        QwirlItemUpdate: {
            /** Question Text */
            question_text?: string;
            /** Options */
            options?: string[];
            /** Owner Answer */
            owner_answer?: string;
            /** Is Soft Deleted */
            is_soft_deleted?: boolean;
        };
        /** QwirlList */
        QwirlList: {
            /** Qwirls */
            qwirls: components["schemas"]["QwirlBase"][];
            /** Count */
            count: number | null;
        };
        /** QwirlQuestion */
        QwirlQuestion: {
            /** Id */
            id: number | null;
            /** Text */
            text: string | null;
            /** Options */
            options: string[];
            /**
             * Is Deleted
             * @default false
             */
            is_deleted: boolean | null;
        };
        /** QwirlQuestionCreate */
        QwirlQuestionCreate: {
            /** Text */
            text: string;
            /** Options */
            options: string[];
        };
        /** QwirlQuestionUpdate */
        QwirlQuestionUpdate: {
            /** Id */
            id: number | null;
            /** Text */
            text: string | null;
            /** Options */
            options: string[];
            /**
             * Is Deleted
             * @default false
             */
            is_deleted: boolean | null;
        };
        /** QwirlResponse */
        QwirlResponse: {
            /** Id */
            id: number;
            /** Questions */
            questions: components["schemas"]["QwirlQuestion"][] | null;
            /** Tags */
            tags: string[] | null;
            /** Created By */
            created_by: number | null;
        };
        /** QwirlResponseBase */
        QwirlResponseBase: {
            /** Id */
            id: number;
            /** Answers */
            answers: components["schemas"]["QwirlAnswer"][] | null;
            /** Qwirl Id */
            qwirl_id: number | null;
            /** Answered By */
            answered_by: number | null;
            user: components["schemas"]["QwirlUser"] | null;
        };
        /** QwirlResponseCreate */
        QwirlResponseCreate: {
            /** Answers */
            answers: components["schemas"]["QwirlAnswerCreate"][];
            /** Qwirl Id */
            qwirl_id: number;
        };
        /** QwirlUpdate */
        QwirlUpdate: {
            /** Questions */
            questions?: components["schemas"]["QwirlQuestionUpdate"][] | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** QwirlUser */
        QwirlUser: {
            /** Name */
            name: string | null;
            /** Username */
            username: string | null;
            /** Id */
            id: number | null;
        };
        /** RefreshTokenOnly */
        RefreshTokenOnly: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RelationshipStatus */
        RelationshipStatus: {
            /** Is Following */
            is_following: boolean;
            /** Is Followed By */
            is_followed_by: boolean;
            /** Is Friend */
            is_friend: boolean;
            /** Wavelength */
            wavelength: number;
        };
        /** ResponseBody */
        ResponseBody: {
            /** Message */
            message: string;
        };
        /** UserFollowerResponse */
        UserFollowerResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Name */
            name: string | null;
            /** Avatar */
            avatar: string | null;
            /** Wavelength */
            wavelength: number;
            /**
             * Is Following
             * @default false
             */
            is_following: boolean;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Name */
            name: string | null;
            /** Phone */
            phone: string | null;
            /** Avatar */
            avatar: string | null;
            /** Header Img */
            header_img: string | null;
            /** Categories */
            categories: string[];
            /** Has Seen Onboarding */
            has_seen_onboarding: boolean | null;
            /** Followers Count */
            followers_count: number;
            /** Following Count */
            following_count: number;
            /** Friends Count */
            friends_count: number;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Username */
            username?: string | null;
            /** Has Seen Onboarding */
            has_seen_onboarding?: boolean | null;
            /** Categories */
            categories?: string[] | null;
        };
        /** UserWithRelationshipResponse */
        UserWithRelationshipResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Name */
            name: string | null;
            /** Phone */
            phone: string | null;
            /** Avatar */
            avatar: string | null;
            /** Header Img */
            header_img: string | null;
            /** Categories */
            categories: string[];
            /** Has Seen Onboarding */
            has_seen_onboarding: boolean | null;
            /** Followers Count */
            followers_count: number;
            /** Following Count */
            following_count: number;
            /** Friends Count */
            friends_count: number;
            relationship: components["schemas"]["RelationshipStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    prompt_smoke_test_hello_world_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBody"];
                };
            };
        };
    };
    external_login_api_v1_users_external_login_get: {
        parameters: {
            query: {
                client_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_callback_api_v1_users_auth_callback_get: {
        parameters: {
            query: {
                client_type: string;
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_access_token_api_v1_users_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenOnly"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_account_api_v1_users_me_delete: {
        parameters: {
            query?: {
                /** @description Whether to permanently delete all user data */
                hard_delete?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_profile_image_api_v1_users_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_profile_image_api_v1_users_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_primary_qwirl_api_v1_users_primary_qwirl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_posts_api_v1_users_posts_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_by_id_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithRelationshipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qwirls_api_v1_qwirl__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_qwirl_api_v1_qwirl__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QwirlCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qwirl_id_api_v1_qwirl__qwirl_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qwirl_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_qwirl_api_v1_qwirl__qwirl_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qwirl_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_qwirl_api_v1_qwirl__qwirl_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qwirl_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QwirlUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_primary_qwirl_api_v1_qwirl_user__user_id__primary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_qwirl_api_v1_qwirl_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_profile_qwirl_item_api_v1_qwirl_me_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QwirlItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlQuestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_profile_qwirl_items_api_v1_qwirl_me_items_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemReorderEntry"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_qwirl_item_api_v1_qwirl_me_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_qwirl_item_api_v1_qwirl_me_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QwirlItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlQuestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_qwirl_response_api_v1_qwirl_responses__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QwirlResponseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlResponseBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qwirl_response_by_id_api_v1_qwirl_responses__response_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                response_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QwirlResponseBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_qwirl_response_api_v1_qwirl_responses__response_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                response_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_v1_question_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    search_question_bank_api_v1_question_bank_search_get: {
        parameters: {
            query: {
                /** @example {"text":"null","categories":[],"tags":[]} */
                params: string;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSearchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_v1_post_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_v1_post__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_v1_post__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_posts_api_v1_post_user__post_owner_id__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                post_owner_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostFetchByID"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vote_api_v1_post__post_id__vote_post: {
        parameters: {
            query: {
                poll_option_id: number;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    like_post_api_v1_post__post_id__like_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlike_post_api_v1_post__post_id__like_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_followers_api_v1_user_follows_followers_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_following_api_v1_user_follows_following_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_friends_api_v1_user_follows_friends_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_followers_by_id_api_v1_user_follows__user_id__followers_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_following_by_id_api_v1_user_follows__user_id__following_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_friends_by_id_api_v1_user_follows__user_id__friends_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_api_v1_user_follows_relationship__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_user_api_v1_user_follows_follow__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_user_api_v1_user_follows_unfollow__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_common_friends_api_v1_user_follows_common_friends__user_id__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFollowerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
