# .github/workflows/main.yml

name: Deploy to Cloud Run

env:
  SERVICE_NAME: qwirl-webapp
  PROJECT_ID: qwirl-459617 # <-- Update with your GCP Project ID
  REGION: asia-south2
  PORT: 3000

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Grant permissions for GCloud auth (needed for Workload Identity Federation)
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          # This workflow uses Workload Identity Federation, which is the recommended
          # authentication method on GCP. It's more secure than using service account keys.
          # Replace with your WIF provider and service account.
          # workload_identity_provider: 'projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/YOUR_POOL/providers/YOUR_PROVIDER'
          service_account: "your-service-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      # Fetches the entire content of the secret. We assume it's in .env format (KEY=VALUE).
      - name: Get .env file from Secret Manager
        id: get_env_file
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            env_vars:projects/${{ env.PROJECT_ID }}/secrets/webapp-env/versions/latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:latest
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:${{ github.sha }}

          build-args: |
            ${{ steps.get_env_file.outputs.env_vars }}

      - name: Deploy to Cloud Run
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --port ${{ env.PORT }} \
            --allow-unauthenticated \
            --timeout=300s
