# .github/workflows/main.yml

name: Deploy to Cloud Run

env:
  SERVICE_NAME: qwirl-webapp
  PROJECT_ID: qwirl-459617 # <-- Update with your GCP Project ID
  REGION: asia-south2
  PORT: 3000
  # Define the secret name for easy reference
  SECRET_NAME: webapp-env

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          service_account: "your-service-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      # Fetches only the VALUE of the secret.
      # IMPORTANT: Your secret should now just be the URL, e.g., "https://..."
      - name: Get API URL from Secret Manager
        id: get_api_url
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            api_url:${{ env.PROJECT_ID }}/secrets/${{ env.SECRET_NAME }}/versions/latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:latest
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:${{ github.sha }}
          # ✅ FIXED: Explicitly set the build argument. This is more robust.
          build-args: |
            NEXT_PUBLIC_API_URL=${{ steps.get_api_url.outputs.api_url }}
          # Enable cache to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/qwirl/qwirl-webapp:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --port ${{ env.PORT }} \
            --allow-unauthenticated \
            --timeout=300s \
            # ✅ FIXED: Set the environment variable for the running service.
            --set-env-vars="NEXT_PUBLIC_API_URL=${{ steps.get_api_url.outputs.api_url }}"
